### ISSUE TITLE
Package directives should allow specifying a world reference for validation.

### ISSUE THREAD

**Issue by peterhuene** [peterhuene/wac#20]
There should be a way for composition authors to specify the world the output component conforms to such that they can ensure the result is of the expected shape.

Some syntax suggestions:

```
package foo:bar targets wasi:http/proxy;
```

Where `targets ...` is optional.

**Comment by peterhuene** [comment]
The validation of the world should occur after resolution and go through the imports and exports to validate each one is present in the targeted world.

**Comment by fibonacci1729** [comment]
Presumably we could use `wit_component::targets` to do this check too but the error returned describing what causes the targets failure is not incredibly informative.

**Comment by peterhuene** [comment]
That's definitely one option, but it's implementation is pretty heavy compared to reusing all of the type information a resolve document already contains (the implementation of `wit_component::targets` encodes a new component and then tries to parse it for a validation error).

It should be pretty straight forward to go through each import, error on an import that's not in the target or a matching one that is mismatched on type, and inverse on the exports (go through only the matching exports and check for mismatched types; i.e. allow more exports than the world specifies).

**Comment by fibonacci1729** [comment]
That makes sense to me!
