### ISSUE TITLE
Turn on the wit and wat features by default.

### ISSUE THREAD

**Issue by rylev** [peterhuene/wac#46]
It's not entirely clear to me why we wouldn't want the wit and wat features on by default. I would suggest turning them on by default. The registry feature still might make sense to have off by default since registries are still quite new.

**Comment by peterhuene** [comment]
The `wat` feature is mostly for the tests, as users will rarely want to author a component in the text format to be used with the tool.

The thinking of having `wit` behind a feature is that eventually wit packages will be from the registry in most cases.

The intention behind both was simply to limit dependencies.

That said, we should probably be defaulting the `wit` feature on as the `registry` feature is defaulted off; we can then default it to off once `registry` is defaulted to on.

Feel free to make that change or I can do so when I'm back on Monday!
